### ISSUE TITLE
isValid and isNotValid

### ISSUE THREAD

**Issue by gianarb** [particle-php/Validator#51]
Hi! I don't know if it's a good idea but in my experience I find very comfortable this type of validator usage..

```php
$v = new Validator;
$v->required('first_name')->length(5);
$v->isValid(['first_name' => 'Berry']); // bool(true).
```
And 
```php
$v = new Validator;
$v->required('first_name')->length(5);
$v->isNotValid(['first_name' => 'Berry']); // bool(false).
```
This approach helps developer to read code.. I don't know if it's only my opinion :)

In your opinion can we try to integrate this API in this library? :)
Thanks a lot for your work! :)

**Comment by RickvdStaaij** [comment]
Hey, thanks for your suggestion. I've discussed this with @berry-langerak. We're all up for explicit naming, adding `isValid` will most likely improve the readability off the code. However, we wan't to keep the API as clean as possible, so we do not want to add multiple functions that pretty much do the same thing. `!$v->isValid()` will probably be good enough instead of implementing isNotValid.

If we decide to change `validate()` to `isValid()`, we would have to release version 2. Or we make `validate()` @deprecated. We will be giving this more thought. Thanks for your suggestion!

**Comment by gianarb** [comment]
oh yes I know that this feature is redundancy but 

```php
if(!$v->isValid()){
}
```
Is very difficult to read.. Explicit this function 
```php
if($v->isNotValid()){
}
```
In my opinion is a good implementation.. :) The code is more readable

**Comment by RickvdStaaij** [comment]
In #57, a ValidationResult is returned by the validate function. In the validationResult you can do isValid and isNotValid. This feature will be released in version 2. Closing issue as it's resolved.
